# Generated by Django 5.1.6 on 2025-03-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vendor', models.CharField(max_length=50)),
                ('pattern', models.CharField(choices=[('Similar Value', 'Similar Value'), ('Similar Reference', 'Similar Reference'), ('Exact Match', 'Exact Match'), ('Similar Date', 'Similar Date'), ('Similar Vendor', 'Similar Vendor'), ('Multiple', 'Multiple')], max_length=50)),
                ('open', models.BooleanField(default=True)),
                ('group_id', models.CharField(max_length=50)),
                ('confidence', models.CharField(max_length=6)),
                ('region', models.CharField(default='North', max_length=50)),
                ('description', models.CharField(default='No description', max_length=250)),
                ('payment_method', models.CharField(default='Credit Card', max_length=50)),
                ('pay_date', models.DateTimeField(blank=True, null=True)),
                ('special_instructions', models.CharField(blank=True, max_length=50, null=True)),
                ('accuracy', models.IntegerField(default=0)),
            ],
        ),
    ]
